version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: training_videos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: demo_password
      MYSQL_DATABASE: training_videos
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: training_videos_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://demo_user:demo_password@mysql:3306/training_videos
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...' &&
        sleep 10 &&
        python init_db.py &&
        python seed_data.py &&
        flask run --host=0.0.0.0 --port=5000
      "

volumes:
  mysql_data: